import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { HeadContent,Link,Outlet,Scripts,createRootRouteWithContext,useRouter } from "@tanstack/react-router";
import { useEffect,type ReactNode } from "react";
import appCss from "../styles.css?url";
import { IntelligenceShell } from "@/components/IntelligenceShell";
import { Button } from "@/components/ui/button";
import { reportLovableError } from "../lib/lovable-error-reporting";
function NotFoundComponent(){return <div className="grid min-h-screen place-items-center bg-background p-6 text-center"><div><p className="font-display text-7xl text-primary">404</p><h1 className="mt-3 text-xl font-semibold">Intelligence view not found</h1><p className="mt-2 text-sm text-muted-foreground">The requested safety intelligence path is unavailable.</p><Button asChild className="mt-5"><Link to="/dashboard">Return to Command Center</Link></Button></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="grid min-h-screen place-items-center bg-background p-6 text-center"><div><h1 className="text-xl font-semibold">Safety intelligence service temporarily unavailable</h1><p className="mt-2 text-sm text-muted-foreground">Retry the request or return to the Command Center.</p><Button className="mt-5" onClick={()=>{router.invalidate();reset()}}>Retry</Button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"theme-color",content:"#0b111a"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=IBM+Plex+Sans:wght@400;500;600&display=swap"},{rel:"icon",href:"/favicon.ico"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><IntelligenceShell><Outlet/></IntelligenceShell></QueryClientProvider>}
