import { Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, CheckCircle2, ChevronRight, CircleAlert, ExternalLink, ShieldAlert, Sparkles } from "lucide-react";
import { LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer,AreaChart,Area,BarChart,Bar } from "recharts";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import type { Report, TrendPoint } from "@/types/intelligence";
export function PageHead({eyebrow,title,subtitle,actions}:{eyebrow?:string;title:string;subtitle:string;actions?:React.ReactNode}){return <div className="mb-6 flex flex-col justify-between gap-4 border-b border-border pb-5 md:flex-row md:items-end"><div>{eyebrow&&<p className="mb-2 text-[11px] font-semibold uppercase tracking-widest text-primary">{eyebrow}</p>}<h1 className="font-display text-2xl font-semibold uppercase md:text-3xl">{title}</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{subtitle}</p></div>{actions}</div>}
export function DemoBadge(){return <span className="inline-flex items-center gap-2 border border-info/30 bg-info/10 px-2 py-1 text-[10px] font-semibold uppercase text-info"><span className="size-1.5 rounded-full bg-info"/>Demo data • synthetic</span>}
export function Panel({title,subtitle,action,children,className}:{title:string;subtitle?:string;action?:React.ReactNode;children:React.ReactNode;className?:string}){return <section className={cn("border border-border bg-card",className)}><div className="flex min-h-14 items-center justify-between gap-3 border-b border-border px-4 py-3"><div><h2 className="text-sm font-semibold uppercase">{title}</h2>{subtitle&&<p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div><div className="p-4">{children}</div></section>}
export function Metric({label,value,trend,tone="neutral"}:{label:string;value:string;trend?:string;tone?:"neutral"|"critical"|"warning"|"success"}){return <div className="relative min-h-28 border border-border bg-card p-4"><span className={cn("absolute left-0 top-0 h-full w-0.5",tone==="critical"?"bg-critical":tone==="warning"?"bg-warning":tone==="success"?"bg-success":"bg-primary")}/><p className="text-[11px] font-semibold uppercase text-muted-foreground">{label}</p><p className="mt-3 font-display text-2xl font-semibold tabular-nums">{value}</p>{trend&&<p className="mt-2 text-xs text-muted-foreground">{trend}</p>}</div>}
export function Status({children,tone="critical"}:{children:React.ReactNode;tone?:"critical"|"warning"|"success"|"info"}){return <span className={cn("inline-flex items-center border px-2 py-0.5 text-[10px] font-bold uppercase",tone==="critical"?"border-critical/30 bg-critical/10 text-critical":tone==="warning"?"border-warning/30 bg-warning/10 text-warning":tone==="success"?"border-success/30 bg-success/10 text-success":"border-info/30 bg-info/10 text-info")}>{children}</span>}
export function TrendChart({data,compact=false}:{data:TrendPoint[];compact?:boolean}){return <div className={compact?"h-44":"h-72"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:10,right:8,left:-24,bottom:0}}><defs><linearGradient id="sifFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-critical)" stopOpacity={.35}/><stop offset="1" stopColor="var(--color-critical)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--color-border)" vertical={false}/><XAxis dataKey="month" tick={{fill:"var(--color-muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"var(--color-muted-foreground)",fontSize:11}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"var(--color-popover)",border:"1px solid var(--color-border)",borderRadius:0,fontSize:12}}/><Area type="monotone" dataKey="sif" stroke="var(--color-critical)" fill="url(#sifFill)" strokeWidth={2}/><Line type="monotone" dataKey="total" stroke="var(--color-info)" dot={false}/></AreaChart></ResponsiveContainer></div>}
export function HorizontalBars({data}:{data:{name:string;value:number}[]}){return <div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:10,right:8}}><CartesianGrid stroke="var(--color-border)" horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={115} tick={{fill:"var(--color-muted-foreground)",fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"var(--color-popover)",border:"1px solid var(--color-border)",borderRadius:0}}/><Bar dataKey="value" fill="var(--color-primary)" radius={0}/></BarChart></ResponsiveContainer></div>}
export function ReportList({reports,onOpen}:{reports:Report[];onOpen:(r:Report)=>void}){return <div className="divide-y divide-border">{reports.map(r=><button key={r.id} onClick={()=>onOpen(r)} className="grid w-full grid-cols-[auto_1fr_auto] items-center gap-3 py-3 text-left hover:bg-accent/40"><span className={cn("size-2 rounded-full",r.sif?"bg-critical":"bg-success")}/><span className="min-w-0"><span className="block text-xs font-semibold">{r.id} · {r.site}</span><span className="mt-1 block truncate text-xs text-muted-foreground">{r.description}</span></span><ChevronRight className="size-4 text-muted-foreground"/></button>)}</div>}
export function RelationshipFlow(){const items=[["Activity","Maintenance"],["Hazard","Electrical Energy"],["Barrier failure","Isolation Verification"],["SIF potential","Detected"],["Consequence","Fatal Electrical Contact"]];return <div className="grid gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{items.map(([k,v],i)=><div key={k} className="contents"><div className="border border-border bg-muted/40 p-3"><p className="text-[10px] uppercase text-muted-foreground">{k}</p><p className="mt-1 text-xs font-semibold">{v}</p></div>{i<items.length-1&&<><ArrowRight className="hidden size-4 text-primary md:block"/><ArrowDown className="mx-auto size-4 text-primary md:hidden"/></>}</div>)}</div>}
export function EmptyState({title="No intelligence found"}:{title?:string}){return <div className="grid min-h-48 place-items-center text-center"><div><CircleAlert className="mx-auto size-6 text-muted-foreground"/><p className="mt-3 text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">Adjust the current filters and try again.</p></div></div>}
